---
  - hosts: 172.31.42.127
    tasks:
      - name: Execute Linux commands from Playbook
        command:  
          cmd:  hostname -f
        register: result_op # register is a variable, not value. we are storing the o/p in result_op
      
      - name:  To display the result of Linux command
        debug:  # To display the result
          msg:  "{{result_op}}"

