---
- hosts:  all
  become: yes
  tasks:

    - name: Install GIT on Redhat Linux
      yum: 
        name: git
        state:  present
      when: ansible_os_family=="RedHat"

    - name: Install GIT on Ubuntu
      apt:
        name: git
        state: present
      when: ansible_os_family=="Debian"
  