---
- hosts: all
  become: yes
  tasks:
    - name: Ping Servers  # Name of task
      ping:    
      
    - name: Install Apache2 on Node server # Name of task only
      apt:                                  # Name of Module
        name: apache2                       # Name of Package
        state: present

    - name: Stop Apache2 Service in Node Server
      service:
        name: apache2
        state: stopped
        
    - name: Restart Apache2 Service in Node Server
      service:
        name: apache2
        state: restarted
