---
  - name: Deploy Jenkins.war on node
    get_url:  
      url:  https://get.jenkins.io/war-stable/2.303.2/jenkins.war
      dest: /opt/tomcat/webapps/jenkins.war
      force_basic_auth: yes

  - name: Deploy Sample Java war from net and place it on node
    get_url:  
      url:  http://csci.viu.ca/~barskym/teaching/DM2012/labs/LAB6/Lab6A.war
      dest: /opt/tomcat/webapps/Lab6A.war
      force_basic_auth: yes