---
  - name: Give the tomcat group ownership over the entire installation directory
    file: 
      path: /opt/tomcat
      group:  tomcat
      recurse: yes
      state:  directory

  - name: Give the tomcat group read access to the conf directory
    file: 
      path: /opt/tomcat/conf
      recurse: yes
      mode: g+r
      state:  directory

  - name: Give the tomcat group Execute access to the conf directory
    file:
      path: /opt/tomcat/conf
      mode: g+x
      state:  directory

  - name: Make the tomcat user the owner of the WEBAPPS folder
    file: 
      path: /opt/tomcat/webapps/
      owner:  tomcat
      recurse: yes
      state:  directory

  - name: Make the tomcat user the owner of the WORK folder
    file: 
      path: /opt/tomcat/work/
      owner:  tomcat
      recurse: yes
      state:  directory

  - name: Make the tomcat user the owner of the TEMP folder
    file: 
      path: /opt/tomcat/temp/
      owner:  tomcat
      recurse: yes
      state:  directory

  - name: Make the tomcat user the owner of the LOGS folder
    file: 
      path: /opt/tomcat/logs/
      owner:  tomcat
      recurse: yes
      state:  directory